import type { AdminData } from './types';

export const mockData: AdminData = {
  siteSettings: {
    logoUrl: '',
    siteName: 'Nora Group',
    tagline: {
      ar: 'فن النجارة الفاخرة والعمارة الخشبية',
      he: 'אמנות הנגרות היוקרתית וארכיטקטורת עץ',
      en: 'Luxury Carpentry & Architecture Woodwork',
    },
    contactEmail: 'info@noragroup.com',
    contactPhone: '+971 4 123 4567',
    contactAddress: {
      ar: 'دبي، الإمارات العربية المتحدة',
      he: 'דובאי, איחוד האמירויות הערביות',
      en: 'Dubai, United Arab Emirates',
    },
    navItems: [
      { id: 'nav-1', label: { ar: 'الرئيسية', he: 'בית', en: 'Home' }, href: '/', order: 0, visible: true },
      { id: 'nav-2', label: { ar: 'من نحن', he: 'אודות', en: 'About' }, href: '/about', order: 1, visible: true },
      { id: 'nav-3', label: { ar: 'مشاريعنا', he: 'פרויקטים', en: 'Projects' }, href: '/projects', order: 2, visible: true },
      { id: 'nav-4', label: { ar: 'المواد والتشطيبات', he: 'חומרים וגימורים', en: 'Materials' }, href: '/materials', order: 3, visible: true },
      { id: 'nav-5', label: { ar: 'خدماتنا', he: 'שירותים', en: 'Services' }, href: '/services', order: 4, visible: true },
      { id: 'nav-6', label: { ar: 'المدونة', he: 'בלוג', en: 'Blog' }, href: '/blog', order: 5, visible: true },
      { id: 'nav-7', label: { ar: 'اتصل بنا', he: 'צור קשר', en: 'Contact' }, href: '/contact', order: 6, visible: true },
    ],
    footerCopyright: {
      ar: '© 2024 مجموعة نورا. جميع الحقوق محفوظة.',
      he: '© 2024 קבוצת נורה. כל הזכויות שמורות.',
      en: '© 2024 Nora Group. All rights reserved.',
    },
    footerLinks: [
      { id: 'fl-1', label: { ar: 'سياسة الخصوصية', he: 'מדיניות פרטיות', en: 'Privacy Policy' }, href: '/privacy' },
      { id: 'fl-2', label: { ar: 'الشروط والأحكام', he: 'תנאים והגבלות', en: 'Terms & Conditions' }, href: '/terms' },
      { id: 'fl-3', label: { ar: 'الأسئلة الشائعة', he: 'שאלות נפוצות', en: 'FAQ' }, href: '/faq' },
    ],
    socialLinks: [
      { id: 'sl-1', platform: 'Instagram', url: 'https://instagram.com/noragroup', icon: 'instagram' },
      { id: 'sl-2', platform: 'LinkedIn', url: 'https://linkedin.com/company/noragroup', icon: 'linkedin' },
      { id: 'sl-3', platform: 'Facebook', url: 'https://facebook.com/noragroup', icon: 'facebook' },
      { id: 'sl-4', platform: 'Pinterest', url: 'https://pinterest.com/noragroup', icon: 'pinterest' },
    ],
  },
  heroSlides: [
    {
      id: 'hero-1',
      imageUrl: 'https://images.pexels.com/photos/8146143/pexels-photo-8146143.jpeg?auto=compress&cs=tinysrgb&w=1920',
      title: { ar: 'حرفية تتجاوز الزمن', he: 'מלאכת יד שמעבר לזמן', en: 'Craftsmanship Beyond Time' },
      subtitle: { ar: 'نصنع تحف خشبية فاخرة تدوم لأجيال', he: 'אנו יוצרים יצירות עץ יוקרתיות שנמשכות לדורות', en: 'We craft luxury wood masterpieces that last for generations' },
      ctaText: { ar: 'اكتشف مشاريعنا', he: 'גלה את הפרויקטים שלנו', en: 'Explore Our Projects' },
      ctaLink: '/projects',
      order: 0,
      published: true,
    },
    {
      id: 'hero-2',
      imageUrl: 'https://images.pexels.com/photos/12441654/pexels-photo-12441654.jpeg?auto=compress&cs=tinysrgb&w=1920',
      title: { ar: 'حيث يلتقي الخشب بالعمارة', he: 'איפה עץ פוגש ארכיטקטורה', en: 'Where Wood Meets Architecture' },
      subtitle: { ar: 'تصاميم خشبية معاصرة تجمع بين الجمال والوظيفة', he: 'עיצובי עץ מודרניים המשלבים יופי ופונקציה', en: 'Contemporary wood designs blending beauty and function' },
      ctaText: { ar: 'تعرف على خدماتنا', he: 'הכירו את השירותים שלנו', en: 'Discover Our Services' },
      ctaLink: '/services',
      order: 1,
      published: true,
    },
    {
      id: 'hero-3',
      imageUrl: 'https://images.pexels.com/photos/35021550/pexels-photo-35021550.jpeg?auto=compress&cs=tinysrgb&w=1920',
      title: { ar: 'لمسة الفخامة في كل تفصيلة', he: 'נגיעת יוקרה בכל פרט', en: 'A Touch of Luxury in Every Detail' },
      subtitle: { ar: 'تشطيبات خشبية راقية ت transform المساحات', he: 'גימורי עץ מהודרים שמשנים מרחבים', en: 'Refined wood finishes that transform spaces' },
      ctaText: { ar: 'شاهد موادنا', he: 'צפה בחומרים שלנו', en: 'View Our Materials' },
      ctaLink: '/materials',
      order: 2,
      published: false,
    },
  ],
  aboutSettings: {
    story: {
      ar: 'تأسست مجموعة نورا عام 2005 برؤية واحدة: إحياء فن النجارة الفاخرة في العصر الحديث. على مدى عقدين من الزمن، نمت شركتنا من ورشة صغيرة إلى استوديو تصميم متكامل، يخدم نخبة العملاء في جميع أنحاء المنطقة. كل قطعة نخرجها تحمل قصة من الشغف والتفاني والدقة التي لا تقبل المساومة.',
      he: 'קבוצת נורה נוסדה בשנת 2005 עם חזון אחד: להחיות את אמנות הנגרות היוקרתית בעידן המודרני. במשך שני עשורים, החברה שלנו גדלה מסדנה קטנה לסטודיו עיצוב משולב, המשרת את עילית הלקוחות ברחבי האזור. כל יצירה שאנו מייצרים נושאת סיפור של תשוקה, מסירות ודיוק שלא מתפשר.',
      en: 'Nora Group was founded in 2005 with a single vision: to revive the art of luxury carpentry in the modern era. Over two decades, our company has grown from a small workshop to an integrated design studio, serving elite clients across the region. Every piece we craft carries a story of passion, dedication, and uncompromising precision.',
    },
    vision: {
      ar: 'أن نكون المرجع الأول في النجارة الفاخرة والعمارة الخشبية في المنطقة، ونحدد معايير الجودة والابتكار لكل من يتبعنا.',
      he: 'להיות ההפניה הראשונה בנגרות יוקרתית וארכיטקטורת עץ באזור, ולקבוע את סטנדרטים של איכות וחדשנות לכל מי שבא אחרינו.',
      en: 'To be the foremost reference in luxury carpentry and wood architecture in the region, setting the standards of quality and innovation for all who follow.',
    },
    mission: {
      ar: 'نلتزم بتقديم تصاميم خشبية استثنائية تجمع بين الحرفية التقليدية والتكنولوجيا الحديثة، مع الحفاظ على الاستدامة البيئية والتفاصيل التي تتجاوز توقعات عملائنا.',
      he: 'אנו מחויבים לספק עיצובי עץ יוצאי דופן המשלבים מלאכת יד מסורתית עם טכנולוגיה מודרנית, תוך שמירה על קיימות סביבתית ופרטים שעולים על ציפיות הלקוחות שלנו.',
      en: 'We are committed to delivering exceptional wood designs that blend traditional craftsmanship with modern technology, while maintaining environmental sustainability and details that exceed our clients\' expectations.',
    },
    featureBanners: [
      { id: 'af-1', icon: 'award', title: { ar: 'جودة معتمدة', he: 'איכות מוסמכת', en: 'Certified Quality' }, description: { ar: 'شهادات دولية في جودة الأخشاب', he: 'תעודות בינלאומיות באיכות עץ', en: 'International certifications in wood quality' } },
      { id: 'af-2', icon: 'leaf', title: { ar: 'صديق للبيئة', he: 'ידידותי לסביבה', en: 'Eco-Friendly' }, description: { ar: 'أخشاب من مصادر مستدامة', he: 'עץ ממקורות ברי קיימא', en: 'Wood from sustainable sources' } },
      { id: 'af-3', icon: 'users', title: { ar: 'حرفيون خبراء', he: 'בעלי מלאכה מומחים', en: 'Master Artisans' }, description: { ar: 'فريق من أمهر النجارين', he: 'צוות של הנגרים המיומנים ביותר', en: 'A team of the most skilled carpenters' } },
      { id: 'af-4', icon: 'clock', title: { ar: 'تسليم في الوقت', he: 'מסירה בזמן', en: 'On-Time Delivery' }, description: { ar: 'نلتزم بالمواعيد المحددة', he: 'אנו מחויבים ללוחות זמנים', en: 'We commit to agreed timelines' } },
    ],
  },
  projects: [
    {
      id: 'proj-1',
      title: { ar: 'فيلا الياسمين', he: 'וילת היסמין', en: 'Villa Yasmin' },
      category: 'Residential',
      imageUrl: 'https://images.pexels.com/photos/8146143/pexels-photo-8146143.jpeg?auto=compress&cs=tinysrgb&w=940',
      galleryImages: [
        'https://images.pexels.com/photos/8146143/pexels-photo-8146143.jpeg?auto=compress&cs=tinysrgb&w=940',
        'https://images.pexels.com/photos/20705886/pexels-photo-20705886.jpeg?auto=compress&cs=tinysrgb&w=940',
      ],
      description: { ar: 'تصميم وتنفيذ خزائن ملابس فاخرة وغرفة ملابس كاملة بأسلوب كلاسيكي معاصر', he: 'עיצוב וביצוע ארונות בגדים יוקרתיים וחדר הלבשה מלא בסגנון קלאסי מודרני', en: 'Design and execution of luxury wardrobes and full walk-in closet in contemporary classic style' },
      woodTypes: ['Teak', 'Walnut'],
      published: true,
      featured: true,
      completedDate: '2024-03-15',
    },
    {
      id: 'proj-2',
      title: { ar: 'مكتب الأرز', he: 'משרד הארז', en: 'Cedar Office' },
      category: 'Commercial',
      imageUrl: 'https://images.pexels.com/photos/35021550/pexels-photo-35021550.jpeg?auto=compress&cs=tinysrgb&w=940',
      galleryImages: [
        'https://images.pexels.com/photos/35021550/pexels-photo-35021550.jpeg?auto=compress&cs=tinysrgb&w=940',
      ],
      description: { ar: 'تشطيب مكتب تنفيذي فاخر بألواح خشبية وتفاصيل نحاسية', he: 'גימור משרד בכיר יוקרתי עם לוחות עץ ופרטי נחושת', en: 'Luxury executive office finishing with wood panels and brass details' },
      woodTypes: ['Oak', 'Mahogany'],
      published: true,
      featured: false,
      completedDate: '2024-01-20',
    },
    {
      id: 'proj-3',
      title: { ar: 'شاليه الجبل', he: 'שאלה הררית', en: 'Mountain Chalet' },
      category: 'Residential',
      imageUrl: 'https://images.pexels.com/photos/28254550/pexels-photo-28254550.jpeg?auto=compress&cs=tinysrgb&w=940',
      galleryImages: [
        'https://images.pexels.com/photos/28254550/pexels-photo-28254550.jpeg?auto=compress&cs=tinysrgb&w=940',
      ],
      description: { ar: 'تصميم داخلي كامل لشاليه جبلي بأجواء دافئة وتفاصيل خشبية أصيلة', he: 'עיצוב פנים מלא לשאלה הררית עם אווירה חמה ופרטי עץ אותנטיים', en: 'Full interior design for a mountain chalet with warm ambiance and authentic wood details' },
      woodTypes: ['Walnut', 'Oak', 'Teak'],
      published: true,
      featured: true,
      completedDate: '2023-11-10',
    },
    {
      id: 'proj-4',
      title: { ar: 'بنتهاوس المارينا', he: 'פנטהאוז מרינה', en: 'Marina Penthouse' },
      category: 'Residential',
      imageUrl: 'https://images.pexels.com/photos/7045352/pexels-photo-7045352.jpeg?auto=compress&cs=tinysrgb&w=940',
      galleryImages: [
        'https://images.pexels.com/photos/7045352/pexels-photo-7045352.jpeg?auto=compress&cs=tinysrgb&w=940',
      ],
      description: { ar: 'مطبخ وحمامات فاخرة بتشطيبات خشبية وأعمدة رخام', he: 'מטבח וחדרי אמבטיה יוקרתיים עם גימורי עץ ועמודי שיש', en: 'Luxury kitchen and bathrooms with wood finishes and marble columns' },
      woodTypes: ['Teak', 'Mahogany'],
      published: false,
      featured: false,
      completedDate: '2024-06-01',
    },
  ],
  materials: [
    {
      id: 'mat-1',
      name: 'Teak',
      type: 'Hardwood',
      textureImageUrl: 'https://images.pexels.com/photos/9996341/pexels-photo-9996341.jpeg?auto=compress&cs=tinysrgb&w=940',
      description: {
        ar: 'خشب التيك البورمي الأصلي، معروف بمقاومته العالية للرطوبة والحشرات. مثالي للأثاث الخارج والداخلي.',
        he: 'עץ טיק בורמזי מקורי, ידוע בעמידותו הגבוהה ללחות וחרקים. אידיאלי לריהוט חיצוני ופנימי.',
        en: 'Authentic Burmese Teak, known for its high resistance to moisture and insects. Ideal for indoor and outdoor furniture.',
      },
      specifications: {
        hardness: 'High',
        density: '655 kg/m³',
        origin: 'Myanmar',
        finishType: 'Natural Oil',
        durability: '50+ years',
        sustainability: 'FSC Certified',
        moistureContent: '12%',
        grainPattern: 'Straight',
        colorTone: 'Golden Brown',
        maintenance: 'Low',
        jankaRating: '1,070 lbf',
        weight: 'Medium-Heavy',
      },
      published: true,
    },
    {
      id: 'mat-2',
      name: 'Oak',
      type: 'Hardwood',
      textureImageUrl: 'https://images.pexels.com/photos/4998279/pexels-photo-4998279.jpeg?auto=compress&cs=tinysrgb&w=940',
      description: {
        ar: 'بلوط أوروبي عالي الجودة، يتميز بنسيج قوي ولون دافئ. خيار ممتاز للأرضيات والأثاث الفاخر.',
        he: 'אלון אירופי באיכות גבוהה, מתאפיין במרקם חזק וצבע חם. בחירה מצוינת לרצפות וריהוט יוקרתי.',
        en: 'Premium European Oak, characterized by strong grain and warm tone. Excellent choice for flooring and luxury furniture.',
      },
      specifications: {
        hardness: 'Very High',
        density: '720 kg/m³',
        origin: 'France',
        finishType: 'Matte Lacquer',
        durability: '40+ years',
        sustainability: 'PEFC Certified',
        moistureContent: '10%',
        grainPattern: 'Wavy',
        colorTone: 'Light Amber',
        maintenance: 'Medium',
        jankaRating: '1,360 lbf',
        weight: 'Heavy',
      },
      published: true,
    },
    {
      id: 'mat-3',
      name: 'Walnut',
      type: 'Hardwood',
      textureImageUrl: 'https://images.pexels.com/photos/8337527/pexels-photo-8337527.jpeg?auto=compress&cs=tinysrgb&w=940',
      description: {
        ar: 'جوز أمريكي فاخر بلون بني داكن غني. مثالي للقطع الفنية والأثاث الراقي.',
        he: 'אגוז אמריקאי יוקרתי בצבע חום כהה עשיר. אידיאלי ליצירות אמנות וריהוט מהודר.',
        en: 'Premium American Walnut with rich dark brown tone. Ideal for artistic pieces and high-end furniture.',
      },
      specifications: {
        hardness: 'High',
        density: '550 kg/m³',
        origin: 'USA',
        finishType: 'Hand-Rubbed Oil',
        durability: '45+ years',
        sustainability: 'FSC Certified',
        moistureContent: '8%',
        grainPattern: 'Curly',
        colorTone: 'Chocolate Brown',
        maintenance: 'Low',
        jankaRating: '1,010 lbf',
        weight: 'Medium',
      },
      published: true,
    },
    {
      id: 'mat-4',
      name: 'Mahogany',
      type: 'Hardwood',
      textureImageUrl: 'https://images.pexels.com/photos/5225594/pexels-photo-5225594.jpeg?auto=compress&cs=tinysrgb&w=940',
      description: {
        ar: 'ماهوغاني هندوراس الأصيل، بلون أحمر بني كلاسيكي. الخيار المفضل للأثاث الكلاسيكي الفاخر.',
        he: 'מהגוני הונדורס מקורי, בצבע חום אדמדם קלאסי. הבחירה המועדפת לריהוט קלאסי יוקרתי.',
        en: 'Authentic Honduras Mahogany, with classic reddish-brown tone. The preferred choice for luxury classic furniture.',
      },
      specifications: {
        hardness: 'Medium-High',
        density: '540 kg/m³',
        origin: 'Honduras',
        finishType: 'Spirit Varnish',
        durability: '50+ years',
        sustainability: 'CITES Regulated',
        moistureContent: '11%',
        grainPattern: 'Interlocked',
        colorTone: 'Reddish Brown',
        maintenance: 'Low',
        jankaRating: '900 lbf',
        weight: 'Medium',
      },
      published: true,
    },
  ],
  services: [
    {
      id: 'svc-1',
      title: { ar: 'تصميم الأثاث الفاخر', he: 'עיצוב ריהוט יוקרתי', en: 'Luxury Furniture Design' },
      icon: 'armchair',
      imageUrl: 'https://images.pexels.com/photos/8146143/pexels-photo-8146143.jpeg?auto=compress&cs=tinysrgb&w=940',
      description: { ar: 'تصميم وتصنيع قطع أثاث فريدة من نوعها بأيدي حرفيين مهرة', he: 'עיצוב וייצור יצירות ריהוט ייחודיות בידי אומנים מיומנים', en: 'Design and manufacture of unique furniture pieces by skilled artisans' },
      steps: [
        { id: 'ss-1', stepNumber: 1, title: { ar: 'الاستشارة', he: 'ייעוץ', en: 'Consultation' }, description: { ar: 'نلتقي بالعميل لفهم رؤيته واحتياجاته', he: 'נפגש עם הלקוח להבין את החזון והצרכים שלו', en: 'We meet the client to understand their vision and needs' } },
        { id: 'ss-2', stepNumber: 2, title: { ar: 'التصميم', he: 'עיצוב', en: 'Design' }, description: { ar: 'نقدم رسومات ثلاثية الأبعاد ومخططات تفصيلية', he: 'מספקים שרטוטים תלת מימדיים ותוכניות מפורטות', en: 'We provide 3D renderings and detailed plans' } },
        { id: 'ss-3', stepNumber: 3, title: { ar: 'التصنيع', he: 'ייצור', en: 'Crafting' }, description: { ar: 'نبدأ التصنيع بأجود الأخشاب والتقنيات التقليدية', he: 'מתחילים בייצור עם עץ האיכותי ביותר וטכניקות מסורתיות', en: 'We begin crafting with premium woods and traditional techniques' } },
        { id: 'ss-4', stepNumber: 4, title: { ar: 'التسليم', he: 'מסירה', en: 'Delivery' }, description: { ar: 'نركب القطعة في موقع العميل مع ضمان شامل', he: 'מתקינים את היצירה באתר הלקוח עם אחריות מלאה', en: 'We install the piece at the client site with full warranty' } },
      ],
      published: true,
    },
    {
      id: 'svc-2',
      title: { ar: 'تشطيبات داخلية', he: 'גימורים פנימיים', en: 'Interior Finishing' },
      icon: 'home',
      imageUrl: 'https://images.pexels.com/photos/35021550/pexels-photo-35021550.jpeg?auto=compress&cs=tinysrgb&w=940',
      description: { ar: 'تشطيبات خشبية كاملة للمساحات السكنية والتجارية', he: 'גימורי עץ מלאים למרחבים מגורים ומסחריים', en: 'Complete wood finishing for residential and commercial spaces' },
      steps: [
        { id: 'ss-5', stepNumber: 1, title: { ar: 'المعاينة', he: 'בדיקה', en: 'Inspection' }, description: { ar: 'نمعاين الموقع ونأخذ القياسات الدقيقة', he: 'בודקים את האתר ולוקחים מדידות מדויקות', en: 'We inspect the site and take precise measurements' } },
        { id: 'ss-6', stepNumber: 2, title: { ar: 'التنفيذ', he: 'ביצוע', en: 'Execution' }, description: { ar: 'ننفذ التشطيبات بأعلى معايير الجودة', he: 'מבצעים את הגימורים בסטנדרטים הגבוהים ביותר', en: 'We execute finishing to the highest quality standards' } },
        { id: 'ss-7', stepNumber: 3, title: { ar: 'التسليم', he: 'מסירה', en: 'Handover' }, description: { ar: 'نسلم المساحة جاهزة مع جولة توضيحية', he: 'מוסרים את המרחב מוכן עם סיור הדגמה', en: 'We hand over the space ready with a walkthrough' } },
      ],
      published: true,
    },
    {
      id: 'svc-3',
      title: { ar: 'الأبواب الفاخرة', he: 'דלתות יוקרה', en: 'Luxury Doors' },
      icon: 'door-open',
      imageUrl: 'https://images.pexels.com/photos/28254550/pexels-photo-28254550.jpeg?auto=compress&cs=tinysrgb&w=940',
      description: { ar: 'تصميم وتصنيع أبواب خشبية فاخرة بتصاميم فريدة', he: 'עיצוב וייצור דלתות עץ יוקרתיות בעיצובים ייחודיים', en: 'Design and manufacture of luxury wooden doors with unique designs' },
      steps: [
        { id: 'ss-8', stepNumber: 1, title: { ar: 'القياس', he: 'מדידה', en: 'Measurement' }, description: { ar: 'نأخذ قياسات دقيقة للفتحة', he: 'לוקחים מדידות מדויקות של הפתח', en: 'We take precise measurements of the opening' } },
        { id: 'ss-9', stepNumber: 2, title: { ar: 'التصميم', he: 'עיצוב', en: 'Design' }, description: { ar: 'نصمم الباب حسب ذوق العميل', he: 'מעצבים את הדלת לפי טעם הלקוח', en: 'We design the door to the client taste' } },
        { id: 'ss-10', stepNumber: 3, title: { ar: 'التركيب', he: 'התקנה', en: 'Installation' }, description: { ar: 'نركب الباب بأحدث الأنظمة والأقفال', he: 'מתקינים את הדלת עם מערכות ומנעולים מודרניים', en: 'We install the door with modern systems and locks' } },
      ],
      published: true,
    },
  ],
  testimonials: [
    {
      id: 'test-1',
      clientName: 'Ahmed Al-Rashid',
      clientTitle: 'Property Developer',
      avatarUrl: '',
      rating: 5,
      text: {
        ar: 'مجموعة نورا حولت رؤيتي إلى واقع. الجودة والتفاصيل تجاوزت كل توقعاتي. أنصح بهم بشدة.',
        he: 'קבוצת נורה הפכה את החזון שלי למציאות. האיכות והפרטים עלו על כל ציפיותי. ממליץ בחום.',
        en: 'Nora Group turned my vision into reality. The quality and details exceeded all my expectations. Highly recommended.',
      },
      published: true,
    },
    {
      id: 'test-2',
      clientName: 'Sarah Goldberg',
      clientTitle: 'Interior Designer',
      avatarUrl: '',
      rating: 5,
      text: {
        ar: 'تعاملت مع فرق كثيرة لكن مجموعة نورا مختلفة. الدقة والاحترافية في كل مرحلة من مراحل العمل.',
        he: 'עבדתי עם צוותים רבים אך קבוצת נורה שונה. דיוק ומקצועיות בכל שלבי העבודה.',
        en: 'I have worked with many teams but Nora Group is different. Precision and professionalism at every stage of work.',
      },
      published: true,
    },
    {
      id: 'test-3',
      clientName: 'Mohammed Hassan',
      clientTitle: 'Hotel Owner',
      avatarUrl: '',
      rating: 4,
      text: {
        ar: 'أنجزوا مشروع فندقنا في الوقت المحدد وبجودة عالية. سأتعامل معهم مرة أخرى بالتأكيد.',
        he: 'השלימו את פרויקט המלון שלנו בזמן ובאיכות גבוהה. אעבוד איתם שוב בוודאות.',
        en: 'They completed our hotel project on time and with high quality. I will definitely work with them again.',
      },
      published: true,
    },
  ],
  faqs: [
    {
      id: 'faq-1',
      question: { ar: 'ما هي مدة تنفيذ مشروع نموذجي؟', he: 'מהי משך ביצוע פרויקט טיפוסי?', en: 'What is the timeline for a typical project?' },
      answer: { ar: 'تتراوح مدة التنفيذ بين 4 إلى 12 أسبوعاً حسب حجم وتعقيد المشروع. نقدم جدولاً زمنياً مفصلاً بعد الاستشارة الأولية.', he: 'משך הביצוע נע בין 4 ל-12 שבועות בהתאם לגודל ומורכבות הפרויקט. אנו מספקים לוח זמנים מפורט לאחר ייעוץ ראשוני.', en: 'Project timelines range from 4 to 12 weeks depending on the scope and complexity. We provide a detailed schedule after the initial consultation.' },
      order: 0,
      published: true,
    },
    {
      id: 'faq-2',
      question: { ar: 'هل تقدمون ضمان على أعمالكم؟', he: 'האם אתם מספקים אחריות על עבודותיכם?', en: 'Do you provide warranty on your work?' },
      answer: { ar: 'نعم، نقدم ضماناً لمدة 5 سنوات على جميع أعمال النجارة والتركيب. الضمان يشمل العيوب التصنيعية والمواد.', he: 'כן, אנו מספקים אחריות ל-5 שנים על כל עבודות הנגרות וההתקנה. האחריות כוללת פגמי ייצור וחומרים.', en: 'Yes, we provide a 5-year warranty on all carpentry and installation work. The warranty covers manufacturing defects and materials.' },
      order: 1,
      published: true,
    },
    {
      id: 'faq-3',
      question: { ar: 'هل يمكنكم العمل مع مواصفات خاصة؟', he: 'האם תוכלו לעבוד עם מפרט מיוחד?', en: 'Can you work with custom specifications?' },
      answer: { ar: 'بالتأكيد. نتخصص في القطع المخصصة ونعمل عن كثب مع العملاء والمصممين لتحقيق أي رؤية.', he: 'בוודאי. אנו מתמחים ביצירות מותאמות אישית ועובדים בצמידות עם לקוחות ומעצבים לממש כל חזון.', en: 'Absolutely. We specialize in custom pieces and work closely with clients and designers to realize any vision.' },
      order: 2,
      published: true,
    },
    {
      id: 'faq-4',
      question: { ar: 'من أين تحصلون على أخشابكم؟', he: 'מאיפה אתם משיגים את העץ שלכם?', en: 'Where do you source your wood?' },
      answer: { ar: 'نستورد أخشابنا من مصادر معتمدة FSC من جميع أنحاء العالم، ضامنين الجودة والاستدامة.', he: 'אנו מייבאים את העץ שלנו ממקורות מוסמכי FSC מכל העולם, תוך הבטחת איכות וקיימות.', en: 'We source our wood from FSC-certified suppliers worldwide, ensuring quality and sustainability.' },
      order: 3,
      published: true,
    },
  ],
  blogPosts: [
    {
      id: 'blog-1',
      title: { ar: 'فن اختيار الخشب المناسب', he: 'אמנות בחירת העץ הנכון', en: 'The Art of Choosing the Right Wood' },
      slug: 'art-of-choosing-wood',
      excerpt: { ar: 'دليل شامل لاختيار النوع المناسب من الخشب لمشروعك', he: 'מדריך מקיף לבחירת סוג העץ הנכון לפרויקט שלך', en: 'A comprehensive guide to choosing the right wood species for your project' },
      content: { ar: 'اختيار الخشب المناسب هو الخطوة الأولى نحو مشروع ناجح...', he: 'בחירת העץ הנכון היא הצעד הראשון לקראת פרויקט מוצלח...', en: 'Choosing the right wood is the first step toward a successful project...' },
      featuredImageUrl: 'https://images.pexels.com/photos/9996341/pexels-photo-9996341.jpeg?auto=compress&cs=tinysrgb&w=940',
      author: 'Nora Group Team',
      publishedAt: '2024-05-10',
      published: true,
      tags: ['Wood', 'Guide', 'Materials'],
    },
    {
      id: 'blog-2',
      title: { ar: 'اتجاهات التصميم الخشبي 2024', he: 'טרנדים בעיצוב עץ 2024', en: 'Wood Design Trends 2024' },
      slug: 'wood-design-trends-2024',
      excerpt: { ar: 'أحدث الاتجاهات في عالم التصميم الخشبي الفاخر', he: 'הטרנדים החמים בעולם עיצוב העץ היוקרתי', en: 'The latest trends in luxury wood design' },
      content: { ar: 'عام 2024 يشهد عودة التصاميم الطبيعية...', he: 'שנת 2024 מביאה חזרה של עיצובים טבעיים...', en: '2024 sees a return to natural designs...' },
      featuredImageUrl: 'https://images.pexels.com/photos/12441654/pexels-photo-12441654.jpeg?auto=compress&cs=tinysrgb&w=940',
      author: 'Nora Group Team',
      publishedAt: '2024-04-22',
      published: true,
      tags: ['Trends', 'Design', '2024'],
    },
    {
      id: 'blog-3',
      title: { ar: 'الحفاظ على الأثاث الخشبي', he: 'שמירה על ריהוט עץ', en: 'Maintaining Wooden Furniture' },
      slug: 'maintaining-wooden-furniture',
      excerpt: { ar: 'نصائح عملية للحفاظ على جمال الأثاث الخشبي لسنوات', he: 'טיפים מעשיים לשמירת יופי ריהוט העץ לשנים', en: 'Practical tips to preserve the beauty of wooden furniture for years' },
      content: { ar: 'العناية المناسبة تضمن طول عمر قطعك الخشبية...', he: 'טיפול נכון מבטיח אורך חיים ליצירות העץ שלך...', en: 'Proper care ensures longevity of your wooden pieces...' },
      featuredImageUrl: 'https://images.pexels.com/photos/8337527/pexels-photo-8337527.jpeg?auto=compress&cs=tinysrgb&w=940',
      author: 'Nora Group Team',
      publishedAt: '2024-03-15',
      published: false,
      tags: ['Maintenance', 'Tips', 'Care'],
    },
  ],
};
