import { randomBytes } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(root, '.env');
const examplePath = resolve(root, '.env.example');

function parseEnv(contents: string): Record<string, string> {
  const parsed: Record<string, string> = {};
  for (const line of contents.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    parsed[key] = value;
  }
  return parsed;
}

function serializeEnv(values: Record<string, string>, header: string): string {
  const lines = [header.trimEnd(), ''];
  for (const [key, value] of Object.entries(values)) {
    lines.push(`${key}=${value}`);
  }
  lines.push('');
  return lines.join('\n');
}

function secret(): string {
  return randomBytes(24).toString('hex');
}

function writeFile(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, 'utf8');
}

function main(): void {
  if (!existsSync(envPath)) {
    if (!existsSync(examplePath)) {
      throw new Error('Missing .env.example');
    }
    copyFileSync(examplePath, envPath);
    process.stdout.write('Created gitignored .env from .env.example\n');
  }

  const values = parseEnv(readFileSync(envPath, 'utf8'));
  if (!values.AUTH_SECRET || values.AUTH_SECRET.length < 32) values.AUTH_SECRET = secret();
  if (!values.REVALIDATE_SECRET || values.REVALIDATE_SECRET.length < 16) {
    values.REVALIDATE_SECRET = secret();
  }
  if (!values.DASHBOARD_OWNER_EMAIL) values.DASHBOARD_OWNER_EMAIL = 'owner@localhost';
  if (!values.DASHBOARD_OWNER_PASSWORD) values.DASHBOARD_OWNER_PASSWORD = 'nora-local-owner';
  if (!values.WEBSITE_REVALIDATE_URL) {
    values.WEBSITE_REVALIDATE_URL = 'http://localhost:3001/api/revalidate';
  }
  if (!values.NEXT_PUBLIC_SITE_URL) values.NEXT_PUBLIC_SITE_URL = 'http://localhost:3001';
  if (values.DATABASE_URL == null) values.DATABASE_URL = '';

  writeFile(
    envPath,
    serializeEnv(values, '# LOCAL only — gitignored. Never commit real credentials.'),
  );

  writeFile(
    resolve(root, 'apps/web/.env.local'),
    serializeEnv(
      {
        DATABASE_URL: values.DATABASE_URL,
        REVALIDATE_SECRET: values.REVALIDATE_SECRET,
        NEXT_PUBLIC_SITE_URL: values.NEXT_PUBLIC_SITE_URL,
      },
      '# Generated by pnpm bootstrap. Gitignored.',
    ),
  );

  writeFile(
    resolve(root, 'apps/Dashboard/.env.local'),
    serializeEnv(
      {
        DATABASE_URL: values.DATABASE_URL,
        AUTH_SECRET: values.AUTH_SECRET,
        DASHBOARD_OWNER_EMAIL: values.DASHBOARD_OWNER_EMAIL,
        DASHBOARD_OWNER_PASSWORD: values.DASHBOARD_OWNER_PASSWORD,
        REVALIDATE_SECRET: values.REVALIDATE_SECRET,
        WEBSITE_REVALIDATE_URL: values.WEBSITE_REVALIDATE_URL,
      },
      '# Generated by pnpm bootstrap. Gitignored.',
    ),
  );

  process.stdout.write('Wrote apps/web/.env.local and apps/Dashboard/.env.local from root .env\n');

  if (!values.DATABASE_URL.trim() || /USER:PASSWORD|\/\/USER:/.test(values.DATABASE_URL)) {
    process.stdout.write(
      'Edit .env and set DATABASE_URL to a real local Postgres login, e.g. postgresql://postgres:your-password@localhost:5432/nora_group\nThen run: pnpm bootstrap\n',
    );
    process.exitCode = 1;
    return;
  }

  process.stdout.write('Running pnpm setup:local (generate, database, migrate, seed)\n');
  const result = spawnSync('pnpm', ['setup:local'], { cwd: root, stdio: 'inherit' });
  process.exitCode = result.status ?? 1;
}

try {
  main();
} catch (error: unknown) {
  const message = error instanceof Error ? error.message : 'bootstrap failed';
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
}
